import { TabWidget , TabWidgetImpl, TabImpl, VerticalBox} from "std-widgets.slint";
import { TranslateInput } from "components.slint";
import { TranslateEdit } from "components.slint";


export component App inherits Window {
    title: "小猪词典";
    TabWidget { 
        Tab {
            title: "词典";
            VerticalBox { 
                TranslateInput {  }
            }
            
        }

        Tab {
            title: "翻译";
            TranslateEdit {  }
        }
    }
}
